### ISSUE TITLE
support parallel uploads

### ISSUE THREAD

**Issue by softprops** [softprops/action-gh-release#1]

**Comment by tunnckoCore** [comment]
For example, multiple releases like in monorepo scenarios?

**Comment by SirWindfield** [comment]
I was wondering too what softprops meant :)

**Comment by softprops** [comment]
Closing this for now. In most of my use cases I have a matrix build which essentially does this for free. I was mainly thinking of a single action step run. Im going to close until I actually have a use case for that.
