### ISSUE TITLE
No Release for v1

### ISSUE THREAD

**Issue by natescherer** [softprops/action-gh-release#100]
Hello,
I just wanted to call out that there's no release for tag v1 and thus the marketplace still tells you to use v0.1.5 from the "Use latest version" button.
Thanks!

**Comment by natescherer** [comment]
Oh and the v1 tag points to a different commit than the v0.1.5 tag if the intention was for them to be the same.

**Comment by softprops** [comment]
the v1 tag had been updated to point at the latest release
