### ISSUE TITLE
Invalid ${{ github.workflow }} in readme.md

### ISSUE THREAD

**Issue by sergey-s-betke** [softprops/action-gh-release#101]
Please, replace `${{github.workflow}}` by `${{github.workspace}}` in readme.md.

**Comment by softprops** [comment]
Hi there. Can you share a bit more context on this issue.

Both of these and more are github context variables documented [here](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context).

What would you be looking for in this change?
