### ISSUE TITLE
Unable to specify a variable in `files:` specification

### ISSUE THREAD

**Issue by kgilmer** [softprops/action-gh-release#102]
My release files are set by environment variables specified in earlier steps.  When I use these variables in the `action-gh-release` `files:` section the variables are taken as string literals rather than the values they represent.

Expected behavior:

`MY_FILE=foo.txt`
`files: $MY_FILE` evaluates to `files: foo.txt`

Actual behavior:

`MY_FILE=foo.txt`
`files: $MY_FILE` evaluates to `files: $MY_FILE`

**Comment by yin1999** [comment]
You should using `${MY_FILE}` instead of `$MY_FILE`.

**Comment by kgilmer** [comment]
Thank you @yin1999

**Comment by CalebEverett** [comment]
`my-file-${MY_FILE}` evaluates to `my-file-${MY_FILE}` instead of `my-file-foo.txt`
