### ISSUE TITLE
Clarify behaviour when there is a conflict

### ISSUE THREAD

**Issue by alexec** [softprops/action-gh-release#103]
It's not clear what the behavior of this action is if:

* The release already exists.
* The release already exists and has a different body.
* The release asset already exists.

I'm doing the following kind of releases

* `v*` - only happens once.
* `master` - happens for every commit to master
* `dev-*` happens for every commit to a branch

For each of these, if the release already exists, I'd like to update it. This means replacing the body and any assets.

**Comment by softprops** [comment]
good call and good question.

there was a recent contribution to this action that would allow for filling in fields with a previous mentioned in [this section](https://github.com/softprops/action-gh-release#-customizing) of the readme

> When the release info keys (such as name, body, draft, prerelease, etc.) are not explicitly set and there is already an existing release for the tag, the release will retain its original info.

That might answer the whole set of question above but let me know if that helps

**Comment by thedmeyer** [comment]
What is the `etc.` of this? Would love some clarification on how to allow for rolling updates of one draft release
