### ISSUE TITLE
Uploading files to existing release resets its properties

### ISSUE THREAD

**Issue by filips123** [softprops/action-gh-release#108]
I have a workflow that runs on a new pushed tag that is created when I create a release from GitHub website. I want that workflow builds some things and then attaches the files to the existing release for that tag that I created.

This works and the files are uploaded correctly to the release without it being overwritten. However, this also resets release's name to tag and clears its pre-release status (and all other properties, excluding description).  This is caused by https://github.com/softprops/action-gh-release/blob/master/src/github.ts#L182-L186 which sets all properties to data provided in workflow config.

I think the solution to this could be to only use data from workflow config when they are explicitly provided (or when a completely new release is created) and otherwise retain them from the existing release.

**Comment by henryiii** [comment]
Same problem. This has been wiping all my release titles.
