### ISSUE TITLE
Merge two Github releases from build matrix output?

### ISSUE THREAD

**Issue by Siedlerchr** [softprops/action-gh-release#11]
First of all thanks for the awesome action! Works like a charm!

I am currently using GItHub actions to build an (ionic cordova) mobile app which is built on linux  (android apk) and mac (ios) in a matrix and upload the asset to Gi
Unfortunately when the jobs finish, I have a separate release for each asset.
I don't know if the api allows this, but would it be somehow possible to merge the releases into one?

**Comment by softprops** [comment]
Ah, the draft : true is a clue. Thanks for sharing. There may be something specific about that case. 

I'm curious if you could do a test where you removed the draft: true and see if you see the same results

**Comment by Siedlerchr** [comment]
@softprops  Thanks for the hint, it was indeed the draft option. When I set draft to false it works fine.
I remember having the same problem with travis as well. So it seems like it's a bug or a "feature" of the github API...

**Comment by softprops** [comment]
It's a fair think to call out. I'll add a note in this actions readme before closing this

**Comment by softprops** [comment]
I did some digging and I think I can do one better. This action uses [this api call](https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name) to fetch a release by tag if it already exists when we update that release. It seem's it only fetches "published" releases   for a tag which is slightly inconvenient for drafts for a tag! But there is a work around by fetching all releases then filtering by tag [mentioned here](https://github.community/t5/GitHub-API-Development-and/Is-there-any-api-to-get-only-draft-releases/td-p/14764) This isn't ideal but may make for a more seamless UX.  I'm going to close this and open a new issue to support that, cross referencing this as the usecase

**Comment by Siedlerchr** [comment]
Ah thanks for the update! This indeed is odd.

**Comment by softprops** [comment]
Consiquence of of maybe adding drafts after they had an API to get a release by tag :/ in any case thanks for surfacing this issue!
