### ISSUE TITLE
Feature support asterisk input for files

### ISSUE THREAD

**Issue by dwisiswant0** [softprops/action-gh-release#114]
Please accept enter asterisk for files. I find it very difficult when I have to rewrite one by one the results of the cross-compile files.

```
🤔 app-v0.0.1-dev_* not include valid file.
```

**Comment by LinqLover** [comment]
For me, [wildcards work](https://github.com/hpi-swa-lab/SqueakByExample-english/blob/e521a283d088f5aa8799c87dc3469a3a72df14e2/.github/workflows/build.yml#L134). Did you maybe add superfluous single quotes around the filename?

**Comment by dwisiswant0** [comment]
Sorry, it's my bad. The prefix name that I fill is incorrect.

**Comment by LinqLover** [comment]
Looks like your `my-file` there is actually a directory. [`files` need to contain files only, though.](https://sourcegraph.com/github.com/softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477/-/blob/src/util.ts?L87) Maybe try `my-*/**/*` instead?

**Comment by bkuhl** [comment]
🤦  You're right... that is a directory.  Thank you - fixed!

**Comment by LinqLover** [comment]
Glad to hear that!
