### ISSUE TITLE
GITHUB_TOKEN is invalidated after time window causing action to fail

### ISSUE THREAD

**Issue by CryZe** [softprops/action-gh-release#12]
On Windows runners this fails with:
```
Run softprops/action-gh-release@v1
   with:
    files: livesplit-core-*.*
  env:
    GITHUB_TOKEN: ***
⚠️ Unexpected error fetching GitHub release for tag refs/tags/v-testing: HttpError: Bad credentials
##[error]Bad credentials
##[error]Node run failed with exit code 1
```

**Comment by CryZe** [comment]
I actually just saw that sometimes even the checkout action fails on Windows with a 401 Unauthorized in a very similar manner:
https://github.com/CryZe/livesplit-core/runs/220191711

**Comment by softprops** [comment]
Now that is weird I can't speak to that but I can pass the info along to gh support.

 Out of curiosity have you seen this happen on any other os but windows?

**Comment by CryZe** [comment]
No, only on Windows.

**Comment by softprops** [comment]
I'll report back here with what il learn from GitHub's support

**Comment by CryZe** [comment]
The 401 seems to affect the Linux runners too. It basically seems to start happening towards the later jobs and then all the remaining jobs error out. So it looks very much like some token expiring. But that's after like 30 minutes or so, which is way too early for this to happen.

**Comment by softprops** [comment]
Following up. Support staff have confirmed these tokens are time limited but have not yet confirmed for how long - https://github.community/t5/GitHub-Actions/GITHUB-TOKEN-is-sometimes-invalid-on-windows-virtual-hosts/m-p/31645/highlight/true#M848

Thanks for adding the extra info about 30 minute range and note that other virtual host os's are affected.  I'm going to update the title of this gh issue to reflect what we believe to be the issue to avoid advertising this action doesn't work with window runners when it does.

**Comment by softprops** [comment]
@CryZe I got some [helpful feedback](https://github.community/t5/GitHub-Actions/GITHUB-TOKEN-is-sometimes-invalid-on-windows-virtual-hosts/m-p/31821/highlight/true#M909) from GitHub's support staff 

> It looks like this is happening because of the number of workflows being queued, it's being rate limited.  We have a fix for this being deployed today.

This looked like a defect on GitHub's end but they may have launched a fix.

If it wouldn't be any trouble, could you give this another spin. Sorry to take up any more of your time.

**Comment by ethomson** [comment]
> If it wouldn't be any trouble, could you give this another spin. Sorry to take up any more of your time.

Yes, please.  We think we've fixed this but let us know if not!  Thanks!

**Comment by CryZe** [comment]
I didn't have much time to test it yet. But from the few runs I've done since then, I didn't have any network errors yet.

**Comment by softprops** [comment]
I'm going to close this issue. I don't think it was related to this action but was hand information for me to have an easy link to track
