### ISSUE TITLE
Does not trigger other workflows anymore

### ISSUE THREAD

**Issue by Umer-Mahmood** [softprops/action-gh-release#132]
I have been using this action to make releases, and based on releases trigger other workflows. But this stopped happening recently.

1. I am using Personall Access Token
2. I can see that release is published successfully.
4. I have tested other release actions with the same personal token, they do trigger my other workflows.

Expected: 
Release published via this action should be able to trigger other workflows if a Personal Access Token, having relavant permission scope, is used.

Observations:
In release history, Under the release I used to see, "(my name) released this xx hours ago", now I see "github-actions released this xx hours ago".

**Comment by softprops** [comment]
thanks for reporting the issue

This was likely a regression in https://github.com/softprops/action-gh-release/pull/83 

I think we can rectify this and restore previous behavior be flipping the order of token resolution in util.ts  I’ll try to get to that this weekend
