### ISSUE TITLE
Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead

### ISSUE THREAD

**Issue by philpettican** [softprops/action-gh-release#135]
`
Run softprops/action-gh-release@v1
  with:
    tag_name: 1.0.0
    name: Release 1.0.0
    target_commitish: XXX
    token: ***
    body: Changes in this Release
  - First Change
  - Second Change
  
    files: artifacts/test.zip
  
    draft: false
    prerelease: false
👩‍🏭 Creating new GitHub release for tag 1.0.0 using commit "XXX"...
⬆️ Uploading test.zip...
Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:437047
    at Array.forEach (<anonymous>)
    at Object.s [as uploadReleaseAsset] (/home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:436958)
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:52043
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:50565
    at new Promise (<anonymous>)
    at i (/home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:50313)
    at Object.t.upload (/home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:51907)
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:44485 {
  name: 'Deprecation'
}`

**Comment by philpettican** [comment]
This looks like it will be addressed once #134 is merged

**Comment by softprops** [comment]
It will. Still working on that one. Note this is only a deprecation warning and not an error so it should not affect your builds

**Comment by softprops** [comment]
this should now be fixed in the latest release. fixes were pushed to v1
