### ISSUE TITLE
Error "not include valid file.",  although there is such a file

### ISSUE THREAD

**Issue by andreyvrn** [softprops/action-gh-release#138]
Error "not include valid file.",  although there is such a file
![image](https://user-images.githubusercontent.com/26858607/128629641-66f9c098-859a-41c4-9664-282df42401df.png)
![image](https://user-images.githubusercontent.com/26858607/128629685-22fa79d3-6b00-4d91-88cf-6131c0e99fef.png)
Code:
https://github.com/andreyvrn/The-Duhamel-integral/blob/7690bfaf1147556c04a7a738c159c38676dfcc68/.github/workflows/lazarus_ci.yml

what am I doing wrong?

**Comment by softprops** [comment]
Hrm. there are two functions of interest when it comes to input files

https://github.com/softprops/action-gh-release/blob/2861dc8673fca411ec3704f41480a3682787659f/src/util.ts#L40

https://github.com/softprops/action-gh-release/blob/2861dc8673fca411ec3704f41480a3682787659f/src/util.ts#L71

I’ll have to have a closer look. I haven’t don’t much testing with windows runners but as far as I know this is known to work

**Comment by softprops** [comment]
this was a similar issue post here with a possible resolution to consolidate the jobs https://github.com/softprops/action-gh-release/issues/79#issuecomment-791386941

another thing I found odd was that in your gh release step you included a [with run DIR](https://github.com/andreyvrn/The-Duhamel-integral/blob/7690bfaf1147556c04a7a738c159c38676dfcc68/.github/workflows/lazarus_ci.yml#L39) input. `run` is not a supported input type for this action. can you try removing that and trying again?

**Comment by andreyvrn** [comment]
Hi! Jobs union works! The problem is the same as in # 79 (comment).
DIR checked the paths, he showed me my file, but for some reason it didn't work out from that folder.
There was also an error without DIR.
Fixed by combining into one job.

**Comment by softprops** [comment]
cool in that case you probably don't even need the extra upload step. I'll close this extra issue for now.

**Comment by andreyvrn** [comment]
@softprops 
Thank you very much!
