### ISSUE TITLE
Add release assets as an output

### ISSUE THREAD

**Issue by m4heshd** [softprops/action-gh-release#152]
This is an extension to #9.

It would be really useful if `outputs` contained something like `assets` which should be an array containing each [response object](https://docs.github.com/en/rest/reference/repos#upload-a-release-asset) from every asset upload. I think you can safely remove the `uploader`  property which is unnecessary IMO.

I'm not sure about the data type though. I think it should be a JSON string which then the user can use with `fromJSON()`. Not sure if it's possible to set it as a proper sequence when setting the output. It's a valuable piece of data to have either way.

I'd do a PR myself but can't put the time aside at the moment. 🥵

**Comment by ncfavier** [comment]
I implemented this in #185
