### ISSUE TITLE
Cannot release files greater than ~2GB

### ISSUE THREAD

**Issue by bankst-oxos** [softprops/action-gh-release#154]
Trying to upload a large file for a release (~4.7GB) and get this error.
```
  Run softprops/action-gh-release@v1
   Error: File size (4788846592) is greater than possible Buffer: 2147483647 bytes
```

**Comment by softprops** [comment]
Unfortunately this is not a limit this action imposes on you. It's a limit of [GitHub's api](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas).
