### ISSUE TITLE
integrate with the new Github release notes generator

### ISSUE THREAD

**Issue by capaj** [softprops/action-gh-release#167]
Github has recently added this button:
![image](https://user-images.githubusercontent.com/1305378/135934705-2896f80d-6efa-4c50-97b4-06e77c5dbdd4.png)

which basically just calls the github API like this:
```
Request URL: https://github.com/capaj/decapi/releases/notes?commitish=0.9.5&tag_name=0.9.5
Request Method: GET
```

and it gets back a changelog.

Would be worth making this the default way to get the changelog when it is not supplied.

**Comment by EdJoPaTo** [comment]
Link to the docs: 
- REST API: https://docs.github.com/en/rest/reference/repos#generate-release-notes-content-for-a-release
- GUI / enduser: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

Personally I see this as opt in via config but yeah, sounds like something this action should support looking forward.
