### ISSUE TITLE
Duplicate files under different directories result in "already exists" (status code 422)

### ISSUE THREAD

**Issue by sgbaird** [softprops/action-gh-release#174]
`.yml`
```yml
    - name: Create Release # https://github.com/softprops/action-gh-release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{steps.build_changelog.outputs.changelog}}
        files: |
          **/*.py
          **/*.csv
          **/*.md
          **/*.yml
          **/*.toml
          **/*.txt
          **/*.ipynb
          **/*.html
          **/*.png
          LICENSE
```

> ```python
> Error: Failed to upload release asset __init__.py. recieved status code 422
> Validation Failed
> [{"resource":"ReleaseAsset","code":"already_exists","field":"name"}]
> ```

I have `__init__.py` under various directories. I take it directory structure is not preserved when using **?

**Comment by softprops** [comment]
Agreed when you specify a file to upload each file is individually downloadable asset what you often want and what most users might expect is an archive of that contains a collection of files
