### ISSUE TITLE
Is it possible to remove the default source zip and tar.gz files from the release?

### ISSUE THREAD

**Issue by MathiasMagnus** [softprops/action-gh-release#220]
If a repo is using git submodules as a means to fetch other parts of the project (not deps) but real modules, so projects that aren't using a monorepo approach have parts of the code missing, because GitHub only zips the repo contents together and not the source tree after recursive cloning.

I created separate CI steps which properly pack up the source ZIP files, but can I remove the default assets automatically created by GitHub? FWIW it's not possible to remove those assets manually either. Even if the release is a draft so manual touch up of the package could be done, it doesn't work.

**Comment by ivanempire** [comment]
I, too, would like to know the answer to this ☕

**Comment by Anton111111** [comment]
I think it impossible because I also can't create release without source manually.

**Comment by ivanempire** [comment]
Yeah the closest you can do (ish) is ignore everything and I guess it creates an empty archive? https://stackoverflow.com/a/58443948

**Comment by Senozoid** [comment]
I think it is safe to assume that unfortunately this isn't going to resolved anytime soon: https://github.com/orgs/community/discussions/6003

**Comment by MrGadget1024** [comment]
I need this too...just an option in GitHub to suppress the source zip and tarball...

![image](https://github.com/softprops/action-gh-release/assets/9826063/b621e1da-ad3b-4687-9e4a-b640dd2d1c37)
