### ISSUE TITLE
Question: will this github step overwrite existing asset already present in release ?

### ISSUE THREAD

**Issue by boxerab** [softprops/action-gh-release#225]
If I push to a release tag multiple times, will this step overwrite older asset ? This is the behaviour I would like.

**Comment by shacha086** [comment]
It would report error

**Comment by boxerab** [comment]
Thanks. I think it would be useful to have an `overwrite` flag.

**Comment by shacha086** [comment]
> Thanks. I think it would be useful to have an `overwrite` flag.

And I thought that it would be better if there is an option that we can choose the behavior of this script when there is a duplicated tag. For example, add assets to an existed release.

**Comment by boxerab** [comment]
that would also work
