### ISSUE TITLE
GitHub release failed with status: 403

### ISSUE THREAD

**Issue by donkeyx** [softprops/action-gh-release#236]
Hey guys,

I am getting a 403 when pushing a release using the action. I have attached the config and a screenshot of my security settings which should be ok. Any help appreciated > 

code block <<

```
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          generate_release_notes: true
          files: |
            bin/tcp-wait.arm64
            bin/tcp-wait.darwin.amd64
            bin/tcp-wait.linux.amd64
            bin/tcp-wait.windows.amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

error <<
```
Run softprops/action-gh-release@v1
👩‍🏭 Creating new GitHub release for tag v0.0.1-test...
⚠️ GitHub release failed with status: 403
undefined
retrying... (2 retries remaining)
👩‍🏭 Creating new GitHub release for tag v0.0.1-test...
⚠️ GitHub release failed with status: 403
undefined
retrying... (1 retries remaining)
👩‍🏭 Creating new GitHub release for tag v0.0.1-test...
⚠️ GitHub release failed with status: 403
undefined
retrying... (0 retries remaining)
❌ Too many retries. Aborting...
```

workflow permissions <<

![image](https://user-images.githubusercontent.com/132504/171749365-d7ec9897-8f3c-4671-9b77-d3af5cb4fe19.png)

**Comment by muellerk22** [comment]
I'm getting the same 403

`      - name: Release
        if: ${{ github.ref == 'refs/heads/cloudzero-optimized' }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: V${{ env.NEXT_TAG }}
          tag_name: v${{ env.NEXT_TAG }}
`

I have the same workflow permissions too.

**Comment by ArjanJ** [comment]
I resolved this by adding this to the yml workflow file
```yml
permissions:
  contents: write
```

**Comment by raviqqe** [comment]
You might also need to disable tag protection rules in your repository if any is defined.

**Comment by simasch** [comment]
Same problem here. 
What's strange is that I have three repos and in two it works

**Comment by sumanthkumarc** [comment]
https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128 worked for me.

**Comment by Timmmm** [comment]
Worth adding this to the readme surely?

**Comment by AshishKapoor** [comment]
Works now! https://github.com/Netix-AI-RnD/budibase-component-camera/commit/909cae09a06576294e81c64a9319d0b5b80969b1

**Comment by HinTak** [comment]
> I resolved this by adding this to my yml workflow file
> 
> ```yaml
> permissions:
>   contents: write
> ```

would it make sense to include this snipplet in the examples in the top-level README, instead of / in addition of mentioning it at the end? I suppose most people are as lazy as me and just leave the default repository permission alone, copy-and-paste the example and edit a bit to try to get it to work. So it would be nice to have the examples working as-is in most people/organizations' settings.

If the repository-level change is preferred, it probably should be mentioned at the top of the readme, instead of the end. I think having it as a per-job/per-action setting is fine for most people.

**Comment by ajithkumar-natarajan** [comment]
I had to enable this setting at my organization level
![image](https://github.com/user-attachments/assets/290ff35c-ced3-4f01-8e77-ddaf0ffd82e2)

**Comment by donkeyx** [comment]
this was resolved with the settings provided by @HinTak << 
    permissions:
      contents: write
      packages: write

**Comment by BoatsDawn** [comment]
This fix helped me: if you already have a ‘latest’ release or tag, just remove it
