### ISSUE TITLE
Download asset support 

### ISSUE THREAD

**Issue by BotellaA** [softprops/action-gh-release#24]
Do you plan to support download of a release asset? It would be a great feature.

**Comment by softprops** [comment]
Hi @BotellaA thanks for the suggestion!

How you you like to see this work?

For reference, I found this which may suit your needs https://github.com/Legion2/download-release-action

**Comment by BotellaA** [comment]
Indeed, the `download-release-action` action looks good. My request was also to have only one action to use/maintain. There are already too many actions to manage Github releases but none of them have the complete set of features (create release, upload/download assets).

Another potential feature would be to have a regex in the `file` input.
