### ISSUE TITLE
chore: Update Node Version to v16

### ISSUE THREAD

**Issue by damienwebdev** [softprops/action-gh-release#249]
I was perusing this repo and noted that https://github.com/softprops/action-gh-release/blob/master/action.yml#L61

Given that [node12 hit end-of-life](https://nodejs.org/en/blog/release/v12.22.12/#notable-changes), it may be a good time to consider upgrading.

**Comment by MikeMcC399** [comment]
https://github.com/actions/runner-images/issues/6482 says "[all OSs] Nodejs 12.x will be removed from the images on November, 14" (2022) so unless this issue is addressed in the next few days workflows using [softprops/action-gh-release](https://github.com/softprops/action-gh-release) may break.

**Comment by davidrunger** [comment]
Personally, I have moved to this GitHub Action: https://github.com/shogo82148/actions-upload-release-asset . It does what I need, and it has no deprecation warnings.[1]

It seems like @softprops is not active on GitHub lately, and I'm not sure if this package has any other maintainers. 😕 🤷‍♂️

![image](https://user-images.githubusercontent.com/8197963/200619748-55d9e755-97b3-4115-97f5-b4d6eedea367.png)

---

[1]: The documentation is a little unclear/misleading, though; I thought at first that one is supposed to write a list of the assets that need to be uploaded to a file called `assets.txt`, and then the action reads that file to determine what to upload. In actuality, that's just an example to generate a file (`assets.txt`) which is then (in that example) uploaded to the release. When one uses the action, one shouldn't create a file called `assets.txt`. Just replace `asset_path: assets.txt` with whichever asset you want to upload.

**Comment by crazy-max** [comment]
> It seems like @softprops is not active on GitHub lately, and I'm not sure if this package has any other maintainers. 😕 🤷‍♂️

Yes looks like it :worried:

If some of you are interested, I forked this repo here: https://github.com/crazy-max/ghaction-github-release

**Comment by cinderblock** [comment]
Fixed in #275

**Comment by MikeMcC399** [comment]
@damienwebdev 

Were you able to check if this is now fixed and no longer giving deprecation warnings?

**Comment by damienwebdev** [comment]
I don't actually use this repo @MikeMcC399 I was just looking at various yaml files and noted the version. I am unable to verify one way or the other.

**Comment by softprops** [comment]
@MikeMcC399 this is now [fixed](https://github.com/softprops/action-gh-release/blob/b4025e2cdd6e8c3ebde4107d4b5a6bac5e66818b/action.yml#L61)
