### ISSUE TITLE
Unhelpful error message during failure: `GitHub release failed with status: undefined`

### ISSUE THREAD

**Issue by matchai** [softprops/action-gh-release#25]
While doing some test runs, I have been consistently encountering the same error, but have been having a difficult time troubleshooting it due to the unhelpful error.

```
⚠️ GitHub release failed with status: undefined, retrying...
```

This persists until the API rate limit is exceeded.

![image](https://user-images.githubusercontent.com/4658208/66038986-91edc780-e54e-11e9-9602-ba1a640bcc30.png)

Here's an example run: https://github.com/matchai/test-rust-actions/runs/244631334

**Suggestions:**
- It might be useful to log the full error object if `error.status` is nully.
- It would be nice if there was a retry limit, or a backoff of sorts. It is retrying 100 times in 15 seconds, making users unable to fix the problem and retry due to API limits being exceeded

**Comment by softprops** [comment]
thanks for reporting the issue @matchai. This is great feedback. I'll follow up
