### ISSUE TITLE
Draft release could not be overwrited

### ISSUE THREAD

**Issue by llaville** [softprops/action-gh-release#284]
Current version v1 is not able to overwrite an existing release in draft mode.
Even if `draft` option is set. 

When can read on project page 

![github com_softprops_action-gh-release](https://user-images.githubusercontent.com/364342/205482364-65646c4b-22ea-4549-9cc7-42c35e431c18.png)

To be able to create a new draft release, we should delete it first by hand !

**Comment by andreasabel** [comment]
> Current version v1 is not able to overwrite an existing release in draft mode.

I think it is good that the default is to append to an existing release rather than to overwrite it.  Thus, you can contribute material to the same draft release from different jobs or workflows.

**Comment by llaville** [comment]
> > Current version v1 is not able to overwrite an existing release in draft mode.
> 
> I think it is good that the default is to append to an existing release rather than to overwrite it. Thus, you can contribute material to the same draft release from different jobs or workflows.

The `body_path` contents is not appended to the release draft. I noticed no updates when a draft already exists and a new job push a new content.

**Comment by WinkelCode** [comment]
![image](https://user-images.githubusercontent.com/29005772/234921468-0c37fe00-c791-465d-a103-e9c9541dbcd3.png)
I am using it like this. It will only delete the previous attachments but name and body is unchanged.
