### ISSUE TITLE
Uploaded assets file name does not support Chinese

### ISSUE THREAD

**Issue by Dunky-Z** [softprops/action-gh-release#288]
Hi,all

When I upload a file name with Chinese characters, 
the Chinese character is automatically deleted. Is there a way to solve it?

Thanks,
Nic

![image](https://user-images.githubusercontent.com/39493223/206461830-c0b664d6-9c18-47f8-b349-11c3900ae6fe.png)
![image](https://user-images.githubusercontent.com/39493223/206461927-d9f92a30-d3c6-48ca-848e-4de34cafa8db.png)

**Comment by 7coil** [comment]
GitHub itself doesn't support CJK in the assets.

![firefox_V4INykWuaz](https://user-images.githubusercontent.com/13886925/210195240-71cffc72-a31b-4fbb-9574-3f839aa4ae57.gif)

**Comment by Dunky-Z** [comment]
@7coil Thanks for replying.
