### ISSUE TITLE
add support for make_latest parameter

### ISSUE THREAD

**Issue by giallu** [softprops/action-gh-release#297]
GH releases have a "make_latest' parameter as detailed in https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release that is not currently supported

**Comment by helloint** [comment]
a nice change. any updates?

**Comment by helloint** [comment]
a nice change. any updates?

**Comment by overbit** [comment]
@softprops Any update on the PR? I see that https://github.com/softprops/action-gh-release/pull/304 has been open a while ago
