### ISSUE TITLE
GitHub release failed with status: 403

### ISSUE THREAD

**Issue by David-Maisonave** [softprops/action-gh-release#347]
I'm getting the [403 error](https://github.com/David-Maisonave/MediaFileDuplicateFinder/actions/runs/4717352126/jobs/8365886774#step:13:29) on my [releases.yml](https://github.com/David-Maisonave/MediaFileDuplicateFinder/blob/master/.github/workflows/releases.yml) script at the Publish step.

I looked at [issue 236](https://github.com/softprops/action-gh-release/issues/236), but the stated fix didn't specify where to put the following two lines.
```
permissions:
  contents: write
```
I tried adding above lines to the [Publish step](https://github.com/David-Maisonave/MediaFileDuplicateFinder/actions/runs/4717372599), but that gave me the following error: _**The workflow is not valid. .github/workflows/releases.yml (Line: 81, Col: 7): Unexpected value 'permissions'**_

Can someone please point me in the right direction to fix this?
Also how do I access the "Workflow Permissions" GUI?

**Comment by zhangt2333** [comment]
Make it as a top-level element or  an element below a job. To see https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs.

**Comment by David-Maisonave** [comment]
>> Make it a top-level element or an element below a job.

Thanks for the help, but I change the logic to a DOS batch script which runs from a desktop.
