### ISSUE TITLE
Update marketplace listing

### ISSUE THREAD

**Issue by NReilingh** [softprops/action-gh-release#35]
When you go through the process of creating a new workflow and searching for actions to use, this one is the top result for "release", but the provided snippet doesn't work:

![image](https://user-images.githubusercontent.com/2458645/71539288-d0a1dc80-2907-11ea-883b-3c2818e3d164.png)

It references v0.1.0, which appears to not be possible to download from Docker successfully anymore since it seems to rely on an image that has been removed. The snippet also misses important requirements that are available on the repo homepage.

The marketplace page mirrors the repo readme, but still lists the v0.1.0 version instead of the 1.0.

**Comment by softprops** [comment]
Can you link me to where to see that @NReilingh? The current lists should reflect the javascript based action interface https://github.com/marketplace/actions/gh-release

**Comment by NReilingh** [comment]
@softprops Here's a screencast that shows where that snippet appears:

https://d.pr/i/dQraE1

Also do realize that the link you just sent still lists v.0.1.0 as the latest release instead of v1.

https://github.com/softprops/action-gh-release/releases

You appear to have tags for subsequent versions, but a "Release" has not been created for them.

**Comment by softprops** [comment]
oh wow, I didn't know that ui existed. thanks for the heads up. I'll try to push another version and see if that updates this ui

**Comment by softprops** [comment]
I pushed a new release for v0.1.5.

**Comment by NReilingh** [comment]
Looks like you got it!
