### ISSUE TITLE
Need for clearer error descriptions

### ISSUE THREAD

**Issue by listenfree** [softprops/action-gh-release#351]
Run softprops/action-gh-release@v1
  with:
    name: 230504-OpenWrt-360T7
    tag_name: 230504-OpenWrt-360T7
    body_path: release.txt
    files: /home/runner/work/OpenWrt-360T7/OpenWrt-360T7/openwrt/bin/targets/mediatek/mt7981/*
    token: ***
  env:
    REPO_URL: https://github.com/listenfree/immortalwrt-mt798x
    REPO_BRANCH: openwrt-21.02
    FEEDS_CONF: feeds.conf.default
    CONFIG_FILE: main.config
    DIY_P1_SH: diy1.sh
    DIY_P2_SH: diy2.sh
    UPLOAD_FIRMWARE: true
    UPLOAD_RELEASE: true
    PUSHPLUS_TOKEN: 
    TZ: Asia/Shanghai
    FIRMWARE_VERSION: 230504
    START_DATE: 2023年05月04日 22点37分02秒
    FIRMWARE: /home/runner/work/OpenWrt-360T7/OpenWrt-360T7/openwrt/bin/targets/mediatek/mt7981
    GITHUB_TOKEN: ***
👩‍🏭 Creating new GitHub release for tag 230504-OpenWrt-360T7...
Error: Cannot read properties of undefined (reading 'data')

everything looks good,but I can't find the real problem,any help please!

**Comment by manulera** [comment]
Hello @listenfree I am having the same problem, did you figure this out?

**Comment by listenfree** [comment]
settings-Actions-general-Workflow permissions-read and write permissons option needed.
