### ISSUE TITLE
The action should fail with an error if the `files:` settings are not valid

### ISSUE THREAD

**Issue by rpdelaney** [softprops/action-gh-release#383]
Example: https://github.com/rpdelaney/downforeveryone/actions/runs/6149726050/job/16686210047

```
🤔 dist/downforeveryone*.whl,dist/downforeveryone*.tar.gz not include valid file.
```

Instead of simply failing, this workflow run instead published a release with all the files in the repo: https://github.com/rpdelaney/downforeveryone/releases/tag/v1.0.5

This is a significant issue because it hides the fact that the action is not doing what the user expected and ends with success. The warnings are buried in the folds so I did not discover the problem until the release archive was already out there and downloaded.

**Comment by damnms** [comment]
i am struggling with this github actions stuff and also felt over this...

![Image](https://github.com/user-attachments/assets/01204bbe-dee4-4d1f-80c7-e9716e2517df)
it looks like from the actions page as if everything is fine while its absolutely not
