### ISSUE TITLE
Add make_latest option

### ISSUE THREAD

**Issue by kdmiltner** [softprops/action-gh-release#385]
When generating a release, the one option that's missing for automating releases for my use cases is `make_latest`. Can this be added as an inputs option to update an existing release tag to be marked as the latest?

For example, if the `tag_name` I input already exists, and `make_latest` is set to true, the functionality would update that release to be marked as the latest.

**Comment by softprops** [comment]
I believe this should be fixed in https://github.com/softprops/action-gh-release/pull/304
