### ISSUE TITLE
GitHub release failed with status: 403

### ISSUE THREAD

**Issue by hannesa2** [softprops/action-gh-release#396]
In a private repo, with this

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.tagger.outputs.tag}}
          prerelease: ${{ env.PRE_RELEASE }}
          name: ${{steps.tagger.outputs.tag}}
          generate_release_notes: true
          files: |
            ./app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

I run into

<img width="458" alt="image" src="https://github.com/softprops/action-gh-release/assets/3314607/900a4049-bf31-4f93-861e-feed60bc35f8">

Does someone has a hint how to solve this ?

**Comment by russellbanks** [comment]
https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128

**Comment by hannesa2** [comment]
Thanks for the advice, it works now
<img width="292" alt="image" src="https://github.com/softprops/action-gh-release/assets/3314607/01ff6d28-e756-47ec-aa1a-3c8da9ab7b32">
