### ISSUE TITLE
Add parameter "allow_update" to control reuse of existing tag_name

### ISSUE THREAD

**Issue by wkmyws** [softprops/action-gh-release#399]
I noticed that when a `tag_name` already exists, 
this script reuses the existing `tag_name `and updates the assets. 

Can we add a parameter `allow_update` to determine whether it is allowed to reuse an existing `tag_name`? 
If `allow_update` is set to false and the `tag_name` already exists, an error should be thrown.

**Comment by vitalykarasik** [comment]
I'm curious if you have an idea what is happening here https://github.com/softprops/action-gh-release/issues/403.
Thank you, Vitaly

**Comment by koss110** [comment]
@wkmyws hope it helps: https://github.com/softprops/action-gh-release/issues/403#issuecomment-1909895544
