### ISSUE TITLE
Replace Node.js 16 with Node.js 20

### ISSUE THREAD

**Issue by Gershon-A** [softprops/action-gh-release#404]
GitHub actions is planning to [deprecate Node 16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). The file existence action is still using Node 16. We are getting this warning that the file exists action should be updated to Node 20

**Comment by nickjosph** [comment]
when is the new version planned to be released?

**Comment by ahmads3-cat** [comment]
> when is the new version planned to be released?

@softprops can you please address this?
