### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by SuzukiHonoka** [softprops/action-gh-release#412]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: softprops/action-gh-release@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by jsirois** [comment]
This was fixed in #406. There is no tag yet containing this fix, but you can use it with `uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981`.

**Comment by SuzukiHonoka** [comment]
> This was fixed in #406. There is no tag yet containing this fix, but you can use it with `uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981`.

Thanks for letting me know.
