### ISSUE TITLE
current version does not match any files issue, previous version is okay

### ISSUE THREAD

**Issue by qwerttvv** [softprops/action-gh-release#416]
The current version of https://github.com/softprops/action-gh-release/tree/20e085ccc73308c2c8e43ab8da4f8d7ecbb94d4e reports an error and then exits 

Error: ⚠️ Pattern 'bin/ packages/x86_64/packages_ci/*ipk' does not match any files. 

Instead of uploading the rest of the matched files, it just exits.

The previous version https://github.com/softprops/action-gh-release/tree/975c1b265e11dd76618af1c374e7981f9a6ff44a would skip the non-existing files and folders and continue to upload the matching files

🤔 Pattern 'bin/packages/x86_64/packages_ci/*ipk' does not match any files. 
👩‍🏭 Creating new GitHub release for tag 2024.03.09-03.43_sm-x86_64... 
⬆️ Uploading sm-x86_64-static.zip... 
⬆️ Uploading sm-x86_64.zip...

yml looks like this 

files: | 
  sm*.zip 
  bin/packages/${{ matrix.arch }}/packages_ci/*ipk

**Comment by softprops** [comment]
I suspect this is a new behavior introduced with https://github.com/softprops/action-gh-release/pull/384 which I believe intended to surface mismatches patterns less quietly

I believe prior to that users had to opt into failing on mismatched patterns https://github.com/softprops/action-gh-release/blob/20e085ccc73308c2c8e43ab8da4f8d7ecbb94d4e/src/main.ts#L30

If I’m reading the message above correctly it sounds like there were some files previously matched and some unmatched. I think the right thing to do is to make the previous change opt in so existing usages are impacted.

I’ll try to get that fix in this weekend.

**Comment by softprops** [comment]
@qwerttvv if you get a chance to check I've made that change in behavior opt in an updated the v2 tag to include those changes
