### ISSUE TITLE
make_latest missing in action.yml

### ISSUE THREAD

**Issue by jr01** [softprops/action-gh-release#418]
![image](https://github.com/softprops/action-gh-release/assets/2624681/69d61c6d-111c-4201-b356-3f9fbfd2dfa5)

https://github.com/softprops/action-gh-release/pull/304

**Comment by softprops** [comment]
Thanks I'll take a look.

**Comment by softprops** [comment]
this should be fixed now 
<img width="542" alt="Screenshot 2024-03-11 at 9 47 55 AM" src="https://github.com/softprops/action-gh-release/assets/2242/be02deb4-49fa-42a4-a404-32a9f5db3b5b">
