### ISSUE TITLE
Ability to default the body to Github's "generate release notes"?

### ISSUE THREAD

**Issue by Erotemic** [softprops/action-gh-release#439]
Github releases recently got a feature where there is a button "Generate release notes" that prepopulates the release notes based on contributors and merged commits. I'm not sure if there is a service I could call to generate that so I can manually specify it in "body", but because it was a github feature, I was wondering if gh-release has the ability to hook into it? (Or if that feature is planned).

**Comment by softprops** [comment]
You'll want to give the `generate_release_notes` a try. See https://github.com/softprops/action-gh-release?tab=readme-ov-file#-customizing for more information
