### ISSUE TITLE
Is title supported as param?

### ISSUE THREAD

**Issue by CoenraadS** [softprops/action-gh-release#496]
Hello

The github CLI support passing a title `-t`: https://cli.github.com/manual/gh_release_create

However I don't see it listed in inputs: https://github.com/softprops/action-gh-release?tab=readme-ov-file#inputs

**Comment by softprops** [comment]
Yes it’s the `name` input which lines up with what it’s called in [GitHubs api](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release)
