### ISSUE TITLE
Do not retry on 422 error from GitHub API

### ISSUE THREAD

**Issue by playpauseandstop** [softprops/action-gh-release#52]
Hi,

First of all, thanks for useful action, it helps a lot.

However, I found pretty scary issue, while provide invalid `tag_name`, it results in ~500 retries to GitHub API and as result rate-limiting my installation ID to make any other requests to GitHub API,

<img width="1080" alt="Screenshot 2020-05-18 at 19 29 42" src="https://user-images.githubusercontent.com/21325/82242499-3c7bf480-993e-11ea-89d5-7980870f3a23.png">

As you see at screenshot below `softprops/action-gh-release` action retries after each [422 error response](https://httpstatuses.com/422) from GitHub API, but it is unexpected behaviour at all, as in the end it results in `HttpError: API rate limit exceeded for installation ID 7068452` error.

I propose to not retry after 422 error from GitHub API, as the error means that something wrong with request data and retry do not change anything, every next request to GitHub API respond same error.

My error was in,

```yaml
tag_name: "20.0.0a1 Release"
```

where I wrongly supply `name` as `tag_name`. I fixed that, but will be able to use GitHub API within GitHub Actions only after my rate limit ban ends.

Thanks in advance and if you see this as reasonable, I would be glad to supply a PR to fix this.

**Comment by softprops** [comment]
> I propose to not retry after 422 error from GitHub API

That sounds great! I'd be happy to take a pr

**Comment by kenorb** [comment]
Same here.
![image](https://user-images.githubusercontent.com/266306/84603671-06238d80-ae88-11ea-9b5e-5415f6ed828d.png)

**Comment by softprops** [comment]
we now limit retries for creating a release to 3 which should address the main issue here
