### ISSUE TITLE
Release do 'not include valid file', but action passed anyway

### ISSUE THREAD

**Issue by kenorb** [softprops/action-gh-release#54]
I had the following error:

![image](https://user-images.githubusercontent.com/266306/84604084-69fb8580-ae8b-11ea-82f0-101c4e55765b.png)

where the filename was invalid, however it didn't fail the action it-self.

I'm aware the filename was invalid, which was my mistake, however I guess the expected behaviour is to fail the step on such error, but instead it's green (which can be challenge to notice that something went wrong).

**Comment by bacongravy** [comment]
I just ran into this issue today. I'd really like an option to have the action fail if it doesn't upload all of the specified files.  Would you be open to a PR that either made that the default behavior, or added a "strict: true" parameter to enable it?  (Changing the default behavior seems like a breaking change that would necessitate a major version bump.)

**Comment by softprops** [comment]
@bacongravy that'd be great.

I'd prefer a more intention. Revealing name though. Strict could mean anything. Perhaps something along the lines of `fail_on_unmatched_asset` or something?

Also it would also be a nice incremental improvement to emit a [`warning`](https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message) when a file is is not matched. These directives bubble up to a more integrated actions ui

**Comment by bacongravy** [comment]
I put up PR #55 with a proposed change.

**Comment by softprops** [comment]
this has since been fixed
