### ISSUE TITLE
HttpError: API rate limit exceeded for installation

### ISSUE THREAD

**Issue by kenorb** [softprops/action-gh-release#56]
I've specified token by `GITHUB_TOKEN`, but I get the following error:

> Unexpected error fetching GitHub release for tag refs/heads/v1.079-dev: HttpError: API rate limit exceeded for installation ID 5238618.

![image](https://user-images.githubusercontent.com/266306/85799262-d7829e00-b736-11ea-8540-6c7014643756.png)

It reads the problem is during 'fetching GitHub release'. Is the action utilizes token in the right way?

**Comment by softprops** [comment]
The "right way" might not be the most accurate way of phrasing the question.

I believe the rate limit for a given token its tied to a workflow run so its shared amongst all other steps and jobs without more context it's difficult to provide more advice. 

I can say that this action is used in many repositories successfully. 

Can you narrow down your usecase and maybe provide a bit more context?

**Comment by kenorb** [comment]
More context which I've found in another job:

```
⚠️ GitHub release failed with status: 422, retrying...
👩‍🏭 Creating new GitHub release for tag  v1.079-dev-beta...
⚠️ GitHub release failed with status: 422, retrying...
👩‍🏭 Creating new GitHub release for tag  v1.079-dev-beta...
⚠️ GitHub release failed with status: 422, retrying...
👩‍🏭 Creating new GitHub release for tag  v1.079-dev-beta...
⚠️ GitHub release failed with status: 403, retrying...
⚠️ Unexpected error fetching GitHub release for tag refs/heads/v1.079-dev: HttpError: API rate limit exceeded for installation ID 5238618.
##[error]API rate limit exceeded for installation ID 5238618.
```

I'm using `softprops/action-gh-release@v1`. See build [812351426](https://github.com/EA31337/EA31337/runs/812351426?check_suite_focus=true#step:8:1055).

I think it's looping and retrying too many times after 422 error.

**Comment by kenorb** [comment]
I think this is dup of #52.

**Comment by softprops** [comment]
Thanks for the extra info. That's be my bet. Does that tag exist?

**Comment by kenorb** [comment]
I had to fix the branch name extraction which was used for the `tag_name` to not put spaces:

```
       - name: Get the current branch name
         shell: bash
-        run: >
+        run: >-
           echo "##[set-output name=branch;]"
           "$(echo ${GITHUB_REF#refs/heads/})"
         id: myref
```

So this is basically duplicate of #52, happening when the tag name is invalid.
