### ISSUE TITLE
[Feature request] Hope to support to create a release to other repos

### ISSUE THREAD

**Issue by Loyalsoldier** [softprops/action-gh-release#58]
I want to create a release and upload assets to other repos. Please support this feature. Thanks!

**Comment by softprops** [comment]
I think this is technically feasibly. At the moment we default to the workflows github repo. Those would need to be added as overridable inputs which fallbacks on the triggered workflows repo

**Comment by Loyalsoldier** [comment]
`actions/create-release` v1.1.4 supports this feature: https://github.com/actions/create-release/releases/tag/v1.1.4

**Comment by NAlexPear** [comment]
I needed this feature in my workflow, so made PR #61 to handle this case
