### ISSUE TITLE
[Security] Update @actions/core to 1.2.6

### ISSUE THREAD

**Issue by past-due** [softprops/action-gh-release#67]
See blog post: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

> Action authors who are using the toolkit should update the @actions/core package to v1.2.6 or greater to get the updated addPath and exportVariable functions.

> Action and workflow authors who are setting environment variables via STDOUT should update any usage of the set-env and add-path workflow commands to use the new environment files.

> If you need to log untrusted information such as issue titles, bodies, or commit messages to STDOUT we recommend that you disable command processing prior to doing that.

**Comment by softprops** [comment]
thanks. we're now on 1.4.0

https://github.com/softprops/action-gh-release/blob/dd98a235fd96fca8a8f9d7b50da723048352cb98/package.json#L23
