### ISSUE TITLE
[Question] Compose for Desktop Multiplatform release

### ISSUE THREAD

**Issue by xetra11** [softprops/action-gh-release#69]
Hey I just am checking out this action and wonder the following.
Is it possible to have three build steps (each for a different OS) and at the end have those three distribution artifacts (*.msi, *.deb, *.macstuff) available to being included in one release?

Atm. from what I understand of the action is that it only works for 1 build to 1 release. In my case I need 3 builds to 1 release. I am not very fresh with Github Actions. Maybe there is a way to merge the artifacts of all three previous builds into one release step?

**Comment by sanjay900** [comment]
You can share artifacts between build steps. What i do is build all three and then save their files as artifacts, then download the artifacts in a single deploy step at the end, and the i create a single release from that. 
Heres my build.yml from a project that does this:
https://github.com/sanjay900/guitar-configurator/blob/master/.github/workflows/build.yml
