### ISSUE TITLE
body 和 body-path到底要怎么写？看不懂。有没有可用的例子？

### ISSUE THREAD

**Issue by liujianchao1995** [softprops/action-gh-release#70]
如题，
body 和 body-path到底要怎么写？看不懂。有没有可用的例子？

**Comment by brianlheim** [comment]
以为body这个是文本，body-path却是文本文件路径：

```json
body: "应用描述"
body_path: 某文件.txt
```

如果你这两都用，会先试图用body_path。

https://github.com/softprops/action-gh-release#inputs

**Comment by yin1999** [comment]
> 以为body这个是文本，body-path却是文本文件路径：
> 
> ```yaml
> body: "应用描述"
> body_path: 某文件.txt
> ```
> 
> 如果你这两都用，会先试图用body_path。
> 
> https://github.com/softprops/action-gh-release#inputs

Due to this issue #71 , the actual behavior is reading `body` first then falling to read the `body_path`.
I have created the pull request #85 to fix it.

translation:
因为以下议题 #71，实际的表现是先读取`body`，如果失败，才会尝试读取`body_path`。
我已提交拉去请求，等待维护人员合并。

**Comment by softprops** [comment]
I believe this has since been fixed in the now included pr mentioned above
