### ISSUE TITLE
Bug: `body` is used without checking the existense of `body_path`.

### ISSUE THREAD

**Issue by perfectmak** [softprops/action-gh-release#71]
Contrary to what is written in the readme:
```
When providing a body and body_path at the same time, body_path will be attempted first, then falling back on body if the path can not be read from.
```

The actual javascript code for [extracting releaseBody](https://github.com/softprops/action-gh-release/blob/master/src/util.ts#L20-L26) checks if `body` is provided and ignores reading the `body_path` outright.

**Comment by softprops** [comment]
Thanks for the bug report. If I don't get to this sooner I'll happily accept a pull request
