### ISSUE TITLE
Warning: Unexpected input(s) 'fail_on_unmatched_files'

### ISSUE THREAD

**Issue by viceice** [softprops/action-gh-release#80]
Getting a warning when using `fail_on_unmatched_files`

```
Warning: Unexpected input(s) 'fail_on_unmatched_files', valid inputs are ['body', 'body_path', 'name', 'tag_name', 'draft', 'prerelease', 'files']
```

https://github.com/visualon/jenkins-gitea-plugin/runs/2057690081?check_suite_focus=true

**Comment by sharpjs** [comment]
Same issue.

https://github.com/sharpjs/Subatomix.Testing/actions/runs/650083795

**Comment by joscha** [comment]
It wasn't defined yet in `v1`, hence why it errors, see: https://github.com/softprops/action-gh-release/blob/v1/action.yml
It was only added in https://github.com/softprops/action-gh-release/pull/55

@softprops can we get a new release, please?

**Comment by marulitua** [comment]
We definitely need a new release

**Comment by joscha** [comment]
@softprops any chance?

**Comment by softprops** [comment]
Sorry for dragging my feet on this I got caught up in some family business. 

I'm try to cut a release this weekend. I just have to make sure everything that's changed is captured in the change log so I don't break existing users workflows

**Comment by softprops** [comment]
this was fixed a while back.
