### ISSUE TITLE
Uploading empty files is failing with a gribish error

### ISSUE THREAD

**Issue by lgmorand** [softprops/action-gh-release#89]
Context

If one of the files listed in _with.files_ is a 0 bit file, the process fails with a gribbish error.

`(node:1729) UnhandledPromiseRejectionWarning: HttpError: Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size is not included in the list"}
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:273881
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1729) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1729) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

IMHO, the action should either:

- allow to upload 0 bytes files (there is no issue here, sometimes info is in file name, not content)
- display a more human readable error in logs

ps: I'm not sure if the error rejecting empty files is on Action side or API side

**Comment by softprops** [comment]
upserting is the new default which should address uploading assets with the same names for the same release. 

as for 0 byte files. i'd have to run some tests. its likely the api does not support these.

**Comment by softprops** [comment]
I tried this in a test repo. GitHub, at least its API, does not support 0 size files

<img width="847" alt="Screen Shot 2021-08-08 at 12 13 28 PM" src="https://user-images.githubusercontent.com/2242/128638455-0df4aa8c-ddea-49db-84da-e4810e3347a4.png">

**Comment by lgmorand** [comment]
sure, but on your screenshot, the error message is crystal clear :) way better than "size is not included in the list" :)
