### ISSUE TITLE
Declare useful outputs

### ISSUE THREAD

**Issue by softprops** [softprops/action-gh-release#9]
GitHub actions defines a way to declare action outputs

https://help.github.com/en/articles/metadata-syntax-for-github-actions#outputs

This may be useful for the purposes of actions that comes after. Some potential outputs ideas

* Gh api release JSON
* List of assets uploaded
* Checksums

**Comment by loicalbertin** [comment]
It would be great to also output the release id

**Comment by softprops** [comment]
a number of outputs have since been [added](https://github.com/softprops/action-gh-release#outputs). closing this for now

**Comment by m4heshd** [comment]
@softprops How about an array of asset IDs? That would be really useful.

**Comment by softprops** [comment]
Can you open a new gh issue specifically for that? I don't want to lose the idea in a closed issue
