### ISSUE TITLE
Control permissions required for this action

### ISSUE THREAD

**Issue by xt0rted** [softprops/action-gh-release#96]
I updated my repo to use the new [control permissions](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/) and had to adjust my workflow to include:
```yaml
permissions:
  contents: write
```

I figured I'd mention this in case anyone else is wondering what the required permissions are to use this. My full workflow can be seen [here](https://github.com/xt0rted/heroicons-tag-helper/blob/main/.github/workflows/release.yml).

**Comment by Myzel394** [comment]
@xt0rted What scopes did you define for your `GITHUB_TOKEN` ?

**Comment by xt0rted** [comment]
@Myzel394 `GITHUB_TOKEN` is [provided by the runner](https://docs.github.com/en/actions/reference/authentication-in-a-workflow) so I'm not setting any scopes, it's using whatever they're providing and I'm locking that down with the permissions feature.

**Comment by softprops** [comment]
very cool thanks for sharing @xt0rted
