### ISSUE TITLE
Support creating discussions during release

### ISSUE THREAD

**Issue by JakeWharton** [softprops/action-gh-release#99]
Newly available feature: https://github.blog/changelog/2021-04-06-releases-support-comments-and-reactions-with-discussion-linking/

Looks like per https://docs.github.com/en/rest/reference/repos#create-a-release there is a new `discussion_category_name` field that will enable this.

**Comment by Athanasius** [comment]
We're experimenting with using this for EDCD/EDMarketConnector releases, and too would like the ability to pre-tick that "Create a discussion" box in the draft release.

**Comment by softprops** [comment]
this should now be in the latest release. the v1 tag has been updated to include this
